global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'log-service'
    static_configs:
      - targets: ['log-service:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'service1'
    static_configs:
      - targets: ['service1:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'service2'
    static_configs:
      - targets: ['service2:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'graylog'
    static_configs:
      - targets: ['graylog:9000']
