apiVersion: v1
kind: Namespace
metadata:
  name: log-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  namespace: log-management
  labels:
    app: log-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: ghcr.io/idris-saddi/log-management/log-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: GRAYLOG_HOST
          value: "graylog"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: log-management
spec:
  selector:
    app: log-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: log-management
  labels:
    app: service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: ghcr.io/idris-saddi/log-management/service1:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: log-management
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
